# Microsoft Developer Studio Generated NMAKE File, Based on MouseTool.dsp
!IF "$(CFG)" == ""
CFG=MouseTool - Win32 Release
!MESSAGE No configuration specified. Defaulting to MouseTool - Win32 Release.
!ENDIF 

!IF "$(CFG)" != "MouseTool - Win32 Release" && "$(CFG)" !=\
 "MouseTool - Win32 Debug"
!MESSAGE Invalid configuration "$(CFG)" specified.
!MESSAGE You can specify a configuration when running NMAKE
!MESSAGE by defining the macro CFG on the command line. For example:
!MESSAGE 
!MESSAGE NMAKE /f "MouseTool.mak" CFG="MouseTool - Win32 Release"
!MESSAGE 
!MESSAGE Possible choices for configuration are:
!MESSAGE 
!MESSAGE "MouseTool - Win32 Release" (based on "Win32 (x86) Application")
!MESSAGE "MouseTool - Win32 Debug" (based on "Win32 (x86) Application")
!MESSAGE 
!ERROR An invalid configuration is specified.
!ENDIF 

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE 
NULL=nul
!ENDIF 

!IF  "$(CFG)" == "MouseTool - Win32 Release"

OUTDIR=.\Release
INTDIR=.\Release
# Begin Custom Macros
OutDir=.\.\Release
# End Custom Macros

!IF "$(RECURSE)" == "0" 

ALL : "$(OUTDIR)\MouseTool.exe" "$(OUTDIR)\MouseTool.bsc"

!ELSE 

ALL : "$(OUTDIR)\MouseTool.exe" "$(OUTDIR)\MouseTool.bsc"

!ENDIF 

CLEAN :
	-@erase "$(INTDIR)\AbtDlg.obj"
	-@erase "$(INTDIR)\AbtDlg.sbr"
	-@erase "$(INTDIR)\ExpiredDialog.obj"
	-@erase "$(INTDIR)\ExpiredDialog.sbr"
	-@erase "$(INTDIR)\ExpiringDlg.obj"
	-@erase "$(INTDIR)\ExpiringDlg.sbr"
	-@erase "$(INTDIR)\ModeChanger.obj"
	-@erase "$(INTDIR)\ModeChanger.sbr"
	-@erase "$(INTDIR)\MouseTool.obj"
	-@erase "$(INTDIR)\MouseTool.pch"
	-@erase "$(INTDIR)\MouseTool.res"
	-@erase "$(INTDIR)\MouseTool.sbr"
	-@erase "$(INTDIR)\MouseToolDlg.obj"
	-@erase "$(INTDIR)\MouseToolDlg.sbr"
	-@erase "$(INTDIR)\OptionsDlg.obj"
	-@erase "$(INTDIR)\OptionsDlg.sbr"
	-@erase "$(INTDIR)\Splash.obj"
	-@erase "$(INTDIR)\Splash.sbr"
	-@erase "$(INTDIR)\StdAfx.obj"
	-@erase "$(INTDIR)\StdAfx.sbr"
	-@erase "$(INTDIR)\StoppedDlg.obj"
	-@erase "$(INTDIR)\StoppedDlg.sbr"
	-@erase "$(INTDIR)\vc50.idb"
	-@erase "$(OUTDIR)\MouseTool.bsc"
	-@erase "$(OUTDIR)\MouseTool.exe"

"$(OUTDIR)" :
    if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

CPP=cl.exe
CPP_PROJ=/nologo /MT /W3 /GX /Zd /O2 /D "WIN32" /D "NDEBUG" /D "_WINDOWS" /D\
 "_MBCS" /FR"$(INTDIR)\\" /Fp"$(INTDIR)\MouseTool.pch" /Yu"stdafx.h"\
 /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /c 
CPP_OBJS=.\Release/
CPP_SBRS=.\Release/

.c{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.c{$(CPP_SBRS)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(CPP_SBRS)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(CPP_SBRS)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

MTL=midl.exe
MTL_PROJ=/nologo /D "NDEBUG" /mktyplib203 /win32 
RSC=rc.exe
RSC_PROJ=/l 0x409 /fo"$(INTDIR)\MouseTool.res" /d "NDEBUG" 
BSC32=bscmake.exe
BSC32_FLAGS=/nologo /o"$(OUTDIR)\MouseTool.bsc" 
BSC32_SBRS= \
	"$(INTDIR)\AbtDlg.sbr" \
	"$(INTDIR)\ExpiredDialog.sbr" \
	"$(INTDIR)\ExpiringDlg.sbr" \
	"$(INTDIR)\ModeChanger.sbr" \
	"$(INTDIR)\MouseTool.sbr" \
	"$(INTDIR)\MouseToolDlg.sbr" \
	"$(INTDIR)\OptionsDlg.sbr" \
	"$(INTDIR)\Splash.sbr" \
	"$(INTDIR)\StdAfx.sbr" \
	"$(INTDIR)\StoppedDlg.sbr"

"$(OUTDIR)\MouseTool.bsc" : "$(OUTDIR)" $(BSC32_SBRS)
    $(BSC32) @<<
  $(BSC32_FLAGS) $(BSC32_SBRS)
<<

LINK32=link.exe
LINK32_FLAGS=winmm.lib /nologo /subsystem:windows /incremental:no\
 /pdb:"$(OUTDIR)\MouseTool.pdb" /machine:I386 /out:"$(OUTDIR)\MouseTool.exe" 
LINK32_OBJS= \
	"$(INTDIR)\AbtDlg.obj" \
	"$(INTDIR)\ExpiredDialog.obj" \
	"$(INTDIR)\ExpiringDlg.obj" \
	"$(INTDIR)\ModeChanger.obj" \
	"$(INTDIR)\MouseTool.obj" \
	"$(INTDIR)\MouseTool.res" \
	"$(INTDIR)\MouseToolDlg.obj" \
	"$(INTDIR)\OptionsDlg.obj" \
	"$(INTDIR)\Splash.obj" \
	"$(INTDIR)\StdAfx.obj" \
	"$(INTDIR)\StoppedDlg.obj"

"$(OUTDIR)\MouseTool.exe" : "$(OUTDIR)" $(DEF_FILE) $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<

!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"

OUTDIR=.\Debug
INTDIR=.\Debug
# Begin Custom Macros
OutDir=.\.\Debug
# End Custom Macros

!IF "$(RECURSE)" == "0" 

ALL : "$(OUTDIR)\MouseTool.exe"

!ELSE 

ALL : "$(OUTDIR)\MouseTool.exe"

!ENDIF 

CLEAN :
	-@erase "$(INTDIR)\AbtDlg.obj"
	-@erase "$(INTDIR)\ExpiredDialog.obj"
	-@erase "$(INTDIR)\ExpiringDlg.obj"
	-@erase "$(INTDIR)\ModeChanger.obj"
	-@erase "$(INTDIR)\MouseTool.obj"
	-@erase "$(INTDIR)\MouseTool.pch"
	-@erase "$(INTDIR)\MouseTool.res"
	-@erase "$(INTDIR)\MouseToolDlg.obj"
	-@erase "$(INTDIR)\OptionsDlg.obj"
	-@erase "$(INTDIR)\Splash.obj"
	-@erase "$(INTDIR)\StdAfx.obj"
	-@erase "$(INTDIR)\StoppedDlg.obj"
	-@erase "$(INTDIR)\vc50.idb"
	-@erase "$(OUTDIR)\MouseTool.exe"
	-@erase "$(OUTDIR)\MouseTool.ilk"
	-@erase "$(OUTDIR)\MouseTool.pdb"

"$(OUTDIR)" :
    if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

CPP=cl.exe
CPP_PROJ=/nologo /MTd /W3 /GX /Zd /Od /D "WIN32" /D "_DEBUG" /D "_WINDOWS" /D\
 "_MBCS" /Fp"$(INTDIR)\MouseTool.pch" /Yu"stdafx.h" /Fo"$(INTDIR)\\"\
 /Fd"$(INTDIR)\\" /FD /c 
CPP_OBJS=.\Debug/
CPP_SBRS=.

.c{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(CPP_OBJS)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.c{$(CPP_SBRS)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cpp{$(CPP_SBRS)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

.cxx{$(CPP_SBRS)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

MTL=midl.exe
MTL_PROJ=/nologo /D "_DEBUG" /mktyplib203 /win32 
RSC=rc.exe
RSC_PROJ=/l 0x409 /fo"$(INTDIR)\MouseTool.res" /d "_DEBUG" 
BSC32=bscmake.exe
BSC32_FLAGS=/nologo /o"$(OUTDIR)\MouseTool.bsc" 
BSC32_SBRS= \
	
LINK32=link.exe
LINK32_FLAGS=winmm.lib /nologo /subsystem:windows /incremental:yes\
 /pdb:"$(OUTDIR)\MouseTool.pdb" /debug /machine:I386\
 /out:"$(OUTDIR)\MouseTool.exe" 
LINK32_OBJS= \
	"$(INTDIR)\AbtDlg.obj" \
	"$(INTDIR)\ExpiredDialog.obj" \
	"$(INTDIR)\ExpiringDlg.obj" \
	"$(INTDIR)\ModeChanger.obj" \
	"$(INTDIR)\MouseTool.obj" \
	"$(INTDIR)\MouseTool.res" \
	"$(INTDIR)\MouseToolDlg.obj" \
	"$(INTDIR)\OptionsDlg.obj" \
	"$(INTDIR)\Splash.obj" \
	"$(INTDIR)\StdAfx.obj" \
	"$(INTDIR)\StoppedDlg.obj"

"$(OUTDIR)\MouseTool.exe" : "$(OUTDIR)" $(DEF_FILE) $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<

!ENDIF 


!IF "$(CFG)" == "MouseTool - Win32 Release" || "$(CFG)" ==\
 "MouseTool - Win32 Debug"
SOURCE=.\AbtDlg.cpp

!IF  "$(CFG)" == "MouseTool - Win32 Release"

DEP_CPP_ABTDL=\
	".\AbtDlg.h"\
	".\MouseTool.h"\
	".\Splash.h"\
	".\trial.h"\
	

"$(INTDIR)\AbtDlg.obj"	"$(INTDIR)\AbtDlg.sbr" : $(SOURCE) $(DEP_CPP_ABTDL)\
 "$(INTDIR)" "$(INTDIR)\MouseTool.pch"


!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"

DEP_CPP_ABTDL=\
	".\AbtDlg.h"\
	".\MouseTool.h"\
	".\Splash.h"\
	".\trial.h"\
	

"$(INTDIR)\AbtDlg.obj" : $(SOURCE) $(DEP_CPP_ABTDL) "$(INTDIR)"\
 "$(INTDIR)\MouseTool.pch"


!ENDIF 

SOURCE=.\ExpiredDialog.cpp

!IF  "$(CFG)" == "MouseTool - Win32 Release"

DEP_CPP_EXPIR=\
	".\expireddialog.h"\
	".\MouseTool.h"\
	".\Splash.h"\
	

"$(INTDIR)\ExpiredDialog.obj"	"$(INTDIR)\ExpiredDialog.sbr" : $(SOURCE)\
 $(DEP_CPP_EXPIR) "$(INTDIR)" "$(INTDIR)\MouseTool.pch"


!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"

DEP_CPP_EXPIR=\
	".\expireddialog.h"\
	".\MouseTool.h"\
	".\Splash.h"\
	

"$(INTDIR)\ExpiredDialog.obj" : $(SOURCE) $(DEP_CPP_EXPIR) "$(INTDIR)"\
 "$(INTDIR)\MouseTool.pch"


!ENDIF 

SOURCE=.\ExpiringDlg.cpp
DEP_CPP_EXPIRI=\
	".\ExpiringDlg.h"\
	".\MouseTool.h"\
	".\Splash.h"\
	

!IF  "$(CFG)" == "MouseTool - Win32 Release"


"$(INTDIR)\ExpiringDlg.obj"	"$(INTDIR)\ExpiringDlg.sbr" : $(SOURCE)\
 $(DEP_CPP_EXPIRI) "$(INTDIR)" "$(INTDIR)\MouseTool.pch"


!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"


"$(INTDIR)\ExpiringDlg.obj" : $(SOURCE) $(DEP_CPP_EXPIRI) "$(INTDIR)"\
 "$(INTDIR)\MouseTool.pch"


!ENDIF 

SOURCE=.\ModeChanger.cpp
DEP_CPP_MODEC=\
	".\ModeChanger.h"\
	".\MouseTool.h"\
	".\Splash.h"\
	

!IF  "$(CFG)" == "MouseTool - Win32 Release"


"$(INTDIR)\ModeChanger.obj"	"$(INTDIR)\ModeChanger.sbr" : $(SOURCE)\
 $(DEP_CPP_MODEC) "$(INTDIR)" "$(INTDIR)\MouseTool.pch"


!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"


"$(INTDIR)\ModeChanger.obj" : $(SOURCE) $(DEP_CPP_MODEC) "$(INTDIR)"\
 "$(INTDIR)\MouseTool.pch"


!ENDIF 

SOURCE=.\MouseTool.cpp

!IF  "$(CFG)" == "MouseTool - Win32 Release"

DEP_CPP_MOUSE=\
	".\commandline.h"\
	".\expireddialog.h"\
	".\ExpiringDlg.h"\
	".\ModeChanger.h"\
	".\MouseTool.h"\
	".\MouseToolDlg.h"\
	".\Splash.h"\
	".\StoppedDlg.h"\
	".\trial.h"\
	

"$(INTDIR)\MouseTool.obj"	"$(INTDIR)\MouseTool.sbr" : $(SOURCE)\
 $(DEP_CPP_MOUSE) "$(INTDIR)" "$(INTDIR)\MouseTool.pch"


!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"

DEP_CPP_MOUSE=\
	".\commandline.h"\
	".\expireddialog.h"\
	".\ExpiringDlg.h"\
	".\ModeChanger.h"\
	".\MouseTool.h"\
	".\MouseToolDlg.h"\
	".\Splash.h"\
	".\StoppedDlg.h"\
	".\trial.h"\
	

"$(INTDIR)\MouseTool.obj" : $(SOURCE) $(DEP_CPP_MOUSE) "$(INTDIR)"\
 "$(INTDIR)\MouseTool.pch"


!ENDIF 

SOURCE=.\MouseTool.rc
DEP_RSC_MOUSET=\
	".\res\bitmap1.bmp"\
	".\res\bmp00001.bmp"\
	".\res\bmp00002.bmp"\
	".\res\bmp00003.bmp"\
	".\res\bmp00004.bmp"\
	".\res\bmp00005.bmp"\
	".\res\bmp00006.bmp"\
	".\res\bmp00007.bmp"\
	".\res\bmp00008.bmp"\
	".\res\bmp00009.bmp"\
	".\res\ddn.bmp"\
	".\res\dfl.bmp"\
	".\res\drag.bmp"\
	".\res\flat.bmp"\
	".\res\header.bmp"\
	".\res\lfl.bmp"\
	".\res\MouseTool.ico"\
	".\res\MouseTool.rc2"\
	".\res\restore.bmp"\
	".\res\rfl.bmp"\
	".\res\rup.bmp"\
	".\trouble.bmp"\
	

"$(INTDIR)\MouseTool.res" : $(SOURCE) $(DEP_RSC_MOUSET) "$(INTDIR)"
	$(RSC) $(RSC_PROJ) $(SOURCE)


SOURCE=.\MouseToolDlg.cpp

!IF  "$(CFG)" == "MouseTool - Win32 Release"

DEP_CPP_MOUSETO=\
	".\AbtDlg.h"\
	".\ModeChanger.h"\
	".\mousedowndlg.h"\
	".\MouseTool.h"\
	".\MouseToolDlg.h"\
	".\OptionsDlg.h"\
	".\Splash.h"\
	".\trial.h"\
	

"$(INTDIR)\MouseToolDlg.obj"	"$(INTDIR)\MouseToolDlg.sbr" : $(SOURCE)\
 $(DEP_CPP_MOUSETO) "$(INTDIR)" "$(INTDIR)\MouseTool.pch"


!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"

DEP_CPP_MOUSETO=\
	".\AbtDlg.h"\
	".\ModeChanger.h"\
	".\mousedowndlg.h"\
	".\MouseTool.h"\
	".\MouseToolDlg.h"\
	".\OptionsDlg.h"\
	".\Splash.h"\
	".\trial.h"\
	

"$(INTDIR)\MouseToolDlg.obj" : $(SOURCE) $(DEP_CPP_MOUSETO) "$(INTDIR)"\
 "$(INTDIR)\MouseTool.pch"


!ENDIF 

SOURCE=.\OptionsDlg.cpp

!IF  "$(CFG)" == "MouseTool - Win32 Release"

DEP_CPP_OPTIO=\
	".\AbtDlg.h"\
	".\MouseTool.h"\
	".\OptionsDlg.h"\
	".\Splash.h"\
	

"$(INTDIR)\OptionsDlg.obj"	"$(INTDIR)\OptionsDlg.sbr" : $(SOURCE)\
 $(DEP_CPP_OPTIO) "$(INTDIR)" "$(INTDIR)\MouseTool.pch"


!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"

DEP_CPP_OPTIO=\
	".\AbtDlg.h"\
	".\MouseTool.h"\
	".\OptionsDlg.h"\
	".\Splash.h"\
	

"$(INTDIR)\OptionsDlg.obj" : $(SOURCE) $(DEP_CPP_OPTIO) "$(INTDIR)"\
 "$(INTDIR)\MouseTool.pch"


!ENDIF 

SOURCE=.\Splash.cpp
DEP_CPP_SPLAS=\
	".\MouseTool.h"\
	".\Splash.h"\
	".\trial.h"\
	

!IF  "$(CFG)" == "MouseTool - Win32 Release"


"$(INTDIR)\Splash.obj"	"$(INTDIR)\Splash.sbr" : $(SOURCE) $(DEP_CPP_SPLAS)\
 "$(INTDIR)" "$(INTDIR)\MouseTool.pch"


!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"


"$(INTDIR)\Splash.obj" : $(SOURCE) $(DEP_CPP_SPLAS) "$(INTDIR)"\
 "$(INTDIR)\MouseTool.pch"


!ENDIF 

SOURCE=.\StdAfx.cpp
DEP_CPP_STDAF=\
	".\StdAfx.h"\
	

!IF  "$(CFG)" == "MouseTool - Win32 Release"

CPP_SWITCHES=/nologo /MT /W3 /GX /Zd /O2 /D "WIN32" /D "NDEBUG" /D "_WINDOWS"\
 /D "_MBCS" /FR"$(INTDIR)\\" /Fp"$(INTDIR)\MouseTool.pch" /Yc"stdafx.h"\
 /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /FD /c 

"$(INTDIR)\StdAfx.obj"	"$(INTDIR)\StdAfx.sbr"	"$(INTDIR)\MouseTool.pch" : \
$(SOURCE) $(DEP_CPP_STDAF) "$(INTDIR)"
	$(CPP) @<<
  $(CPP_SWITCHES) $(SOURCE)
<<


!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"

CPP_SWITCHES=/nologo /MTd /W3 /GX /Zd /Od /D "WIN32" /D "_DEBUG" /D "_WINDOWS"\
 /D "_MBCS" /Fp"$(INTDIR)\MouseTool.pch" /Yc"stdafx.h" /Fo"$(INTDIR)\\"\
 /Fd"$(INTDIR)\\" /FD /c 

"$(INTDIR)\StdAfx.obj"	"$(INTDIR)\MouseTool.pch" : $(SOURCE) $(DEP_CPP_STDAF)\
 "$(INTDIR)"
	$(CPP) @<<
  $(CPP_SWITCHES) $(SOURCE)
<<


!ENDIF 

SOURCE=.\StoppedDlg.cpp
DEP_CPP_STOPP=\
	".\MouseTool.h"\
	".\Splash.h"\
	".\StoppedDlg.h"\
	

!IF  "$(CFG)" == "MouseTool - Win32 Release"


"$(INTDIR)\StoppedDlg.obj"	"$(INTDIR)\StoppedDlg.sbr" : $(SOURCE)\
 $(DEP_CPP_STOPP) "$(INTDIR)" "$(INTDIR)\MouseTool.pch"


!ELSEIF  "$(CFG)" == "MouseTool - Win32 Debug"


"$(INTDIR)\StoppedDlg.obj" : $(SOURCE) $(DEP_CPP_STOPP) "$(INTDIR)"\
 "$(INTDIR)\MouseTool.pch"


!ENDIF 


!ENDIF 

